### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'mH'

### ISSUE THREAD

**Issue by Sumanth181099** [ssssshwan/TLDR#3]
Thanks for the good work. When trying to train the model using the command given in the ReadMe file, attribute error pops up at line 186 in the photo_wct_batch.py file.
Any help would be appreciated.

**Comment by DNGcv** [comment]
Have you solved this problem? I have the same problem.
Any help would be appreciated.

**Comment by LyTingHub** [comment]
This may be a problem with the pytorch version. You can see torch.Tensor.mH in torch1.12([torch.Tensor.mH](https://pytorch.org/docs/1.12/tensors.html#torch.Tensor.mH))

**Comment by ssssshwan** [comment]
Sorry for the delay and thanks for reaching out!

I double-checked the torch version and 1.8.0 is the right version. I got this part of the code from [FastPhotoWCT](https://github.com/NVIDIA/FastPhotoStyle). You might be able to refer to its development environment.
